version: '3.8'

services:
  app:
    build: .
    volumes:
      - /app/sock
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"